### ISSUE TITLE
Spanish is horribly translated

### ISSUE THREAD

**Issue by NitroXenon** [NitroXenon/TerrariumTV-Localization#6]
Some users reported that Spanish translation is horrbly translated. 

@InfiDim42

**Comment by InfiDim42** [comment]
Well to be fair some of the words don't really have context outside their original language, and even the original translations had some issues.
I'll look into it more closely and try to be more accurate.

**Comment by NitroXenon** [comment]
```and even the original translations had some issues```
Could you tell me more about it? I'm not an English native speaker tho.

**Comment by InfiDim42** [comment]
It's just grammar that needs to be fixed. When I fix the Spanish translations, I'll fix the English as well.

**Comment by NitroXenon** [comment]
Great

**Comment by NitroXenon** [comment]
The Spanish translation seems to be improved a lot. Close this issue.
